services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=kotoba
      - POSTGRES_USER=kotoba
      - POSTGRES_PASSWORD=kotoba
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats
    restart: always
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data:
