export enum LanguageCode {
  EN_US = 'en-US', // English (United States)
  ZH_CN = 'zh-CN', // Chinese (Simplified, China)
  HI_IN = 'hi-IN', // Hindi (India)
  ES_ES = 'es-ES', // Spanish (Spain)
  FR_FR = 'fr-FR', // French (France)
  AR_SA = 'ar-SA', // Arabic (Saudi Arabia)
  BN_IN = 'bn-IN', // Bengali (India)
  RU_RU = 'ru-RU', // Russian (Russia)
  PT_BR = 'pt-BR', // Portuguese (Brazil)
  ID_ID = 'id-ID', // Indonesian (Indonesia)
  DE_DE = 'de-DE', // German (Germany)
  JA_JP = 'ja-JP', // Japanese (Japan)
  KO_KR = 'ko-KR', // Korean (South Korea)
  VI_VN = 'vi-VN', // Vietnamese (Vietnam)
  IT_IT = 'it-IT', // Italian (Italy)
  TR_TR = 'tr-TR', // Turkish (Turkey)
  FA_IR = 'fa-IR', // Persian (Iran)
  PL_PL = 'pl-PL', // Polish (Poland)
  UK_UA = 'uk-UA', // Ukrainian (Ukraine)
}
